### ISSUE TITLE
Arreglar notificación de noticias HTML

### ISSUE THREAD

**Issue by tomasguti** [tomasguti/utn-movil-backend#22]
Se ve mal en el texto de la notificación cuando la noticia es HTML

Se puede hacer algo tipo:

Título Notificación: Departamento Sistemas
Cuerpo Notificación: Hay una nueva noticia de este canal.

**Comment by spaciuk** [comment]
Veo, igual para las notificaciones no sería mejor mostrar el Canal y el Titulo de la noticia nomás ?

**Comment by tomasguti** [comment]
Sí, eso estaría mejor.
