### ISSUE TITLE
El campo de texto del cuerpo de noticias.html es muy chico

### ISSUE THREAD

**Issue by tomasguti** [tomasguti/utn-movil-backend#23]
Es muy molesto editar una noticia en un espacio tan chico, si lo agrando un poco a veces se vuelve a achicar después. Hacer que por defecto sea más alto, el triple de lo que es ahora por lo menos.

**Comment by spaciuk** [comment]
Para esto, si seteamos "x"cantidad de filas iniciales, puede que en la pc se vea bien, pero en el celu va a haber que scrollear, aunque es una opción. Capaz sería mejor hacer algo como "height: 60%" al textarea del wysihtml5, si es que se puede

**Comment by spaciuk** [comment]
Se ponen 13 filas, en vez de 4.
