### ISSUE TITLE
No puedo acceder al backend

### ISSUE THREAD

**Issue by jcramosfrsf** [tomasguti/utn-movil-backend#26]
Cuando pruebo con el link que nos pasaron para ingresar, obtengo el error: Cannot GET /

**Comment by tomasguti** [comment]
Por la migración a HTTPS la dirección nueva es https://104.197.204.211:3443
Seguro de error de certificado porque lo autofirmamos por ahora. Pero se puede entrar igual en Avanzadas>Continuar de todos modos

**Comment by tomasguti** [comment]
Problema de puertos bloqueados. Solucionado.
